config/routes.rb
MiniBizspot::Application.routes.draw do

  resources :bookings

  resources :offers

  resources :products

  devise_for :users, :controllers => {
                       :sessions => "users/sessions",
                       :confirmations => "users/confirmations",
                       :passwords => "users/passwords",
                       :registrations => "users/registrations"
                   }

  devise_scope :user do
    get "sign_up" => "users/registrations#new"
    get "sign_in" => "users/sessions#new"
    get "sign_out" => "users/sessions#destroy"
  end
  resources :home do
    collection do
      get :products
      get :offers
    end
  end
  resources :businesses
  resources :profiles
  resources :customer_businesses
  resources :customer_offers

  root :to => 'home#products'

end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
  attr_accessible :name
  has_many :businesses
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  before_filter :authenticate_user!

  before_filter :set_business, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @businesses = current_user.businesses
    respond_with(@businesses)
  end

  def show
    respond_with(@business)
  end

  def new
    @business = Business.new
    respond_with(@business)
  end

  def edit
  end

  def create
    @business = Business.new(params[:business])
    @business.save
    respond_with(@business)
  end

  def update
    @business.update_attributes(params[:business])
    respond_with(@business)
  end

  def destroy
    @business.destroy
    respond_with(@business)
  end

  private
  def set_business
    @business = Business.find(params[:id])
  end
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% @business.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <h2>DETAILS:</h2>

  <div class="field">
    <%= f.label :business_type_id %><br/>
    <%= f.select :business_type_id, options_from_collection_for_select(BusinessType.all, :id, :name, f.object.business_type_id) %>
  </div>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br/>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :tag_line %><br/>
    <%= f.text_field :tag_line %>
  </div>

  <h2>LOCATION ON MAP:</h2>

  <div class="field">
    <%= f.label :latitude %><br/>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br/>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>My Businesses</h1>

<table>
  <tr>
    <th>Business type</th>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Tag line</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @businesses.each do |business| %>
    <tr>
      <td><%= business.business_type.name %></td>
      <td><%= business.name %></td>
      <td><%= business.description %></td>
      <td><%= business.address %></td>
      <td><%= business.tag_line %></td>
      <td><%= link_to 'Products', products_path(:business_id => business.id) %></td>
      <td><%= link_to 'Details', business %></td>
      <td><%= link_to 'Edit', edit_business_path(business) %></td>
      <td><%= link_to 'Destroy', business, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<h2>DETAILS:</h2>

<p>
  <b>Business type:</b>
  <%= @business.business_type.name %>
</p>

<p>
  <b>Name:</b>
  <%= @business.name %>
</p>

<p>
  <b>Description:</b>
  <%= @business.description %>
</p>

<p>
  <b>Address:</b>
  <%= @business.address %>
</p>

<p>
  <b>Tag line:</b>
  <%= @business.tag_line %>
</p>

<h2>LOCATION ON MAP:</h2>

<p>
  <b>Latitude:</b>
  <%= @business.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @business.longitude %>
</p>


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>