config/routes.rb
MiniBizspot::Application.routes.draw do

  resources :bookings

  resources :offers

  resources :products

  devise_for :users, :controllers => {
                       :sessions => "users/sessions",
                       :confirmations => "users/confirmations",
                       :passwords => "users/passwords",
                       :registrations => "users/registrations"
                   }

  devise_scope :user do
    get "sign_up" => "users/registrations#new"
    get "sign_in" => "users/sessions#new"
    get "sign_out" => "users/sessions#destroy"
  end
  resources :home do
    collection do
      get :products
      get :offers
    end
  end
  resources :businesses
  resources :profiles
  resources :customer_businesses
  resources :customer_offers

  root :to => 'home#products'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :description, :end_at, :product_id, :start_at, :user_id, :status

  belongs_to :user
  belongs_to :product

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_filter :authenticate_user!

  before_filter :set_booking, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if current_user.business_owner?
      @bookings = Booking.where(:product_id => Product.where(:business_id => current_user.businesses.map(&:id)).map(&:id))
    else
      @bookings = current_user.bookings
    end
    @bookings = Booking.all
    respond_with(@bookings)
  end

  def show
    respond_with(@booking)
  end

  def new
    @product = Product.find_by_id(params[:product_id])
    @booking = Booking.new
    respond_with(@booking)
  end

  def edit
    @product = Product.find_by_id(params[:product_id])
  end

  def create
    @booking = Booking.new(params[:booking])
    @booking.save
    respond_with(@booking)
  end

  def update
    @booking.update_attributes(params[:booking])
    respond_with(@booking)
  end

  def destroy
    @product = Product.find_by_id(params[:product_id])
    @booking.destroy
    respond_with(@booking)
  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @booking.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :product_id, :value => @product.id %>
  <% if current_user.business_owner? %>
    <%= f.select :status, ["Accepted", "Rejected"] %>
  <% else %>
    <%= f.hidden_field :status, :value => "pending" %>
  <% end %>

  <div class="field">
    <%= f.label :start_at %><br/>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br/>
    <%= f.datetime_select :end_at %>
  </div>
  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Start at</th>
    <th>End at</th>
    <th>Description</th>
    <th>Status</th>
    <% if current_user.business_owner? %>
      <th>User</th>
      <th></th>
    <% end %>
    <th></th>
    <th></th>
  </tr>

  <% @bookings.each do |booking| %>
    <tr>
      <td><%= booking.product.name %></td>
      <td><%= booking.start_at %></td>
      <td><%= booking.end_at %></td>
      <td><%= booking.description %></td>
      <td><%= booking.status %></td>
      <% if current_user.business_owner? %>
        <td><%= booking.user.email %></td>
        <td>
          <% if booking.status == "Pending" %>
            <%= link_to 'Accept|Reject', edit_booking_path(:id => booking.id, :product_id => booking.product.id) %>|
          <% elsif booking.status == "Accepted" %>
            <%= link_to 'Reject', edit_booking_path(:id => booking.id, :product_id => booking.product.id) %>
          <% else %>
            <%= link_to 'Accept', edit_booking_path(:id => booking.id, :product_id => booking.product.id) %>
          <% end %>
        </td>
      <% else %>
        <td><%= link_to 'Edit', edit_booking_path(:id => booking.id, :product_id => booking.product.id) %></td>
      <% end %>
      <td><%= link_to 'Destroy', booking_path(:id => booking.id, :product_id => booking.product.id), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br/>
<% unless current_user.business_owner? %>
  <%= link_to 'New Booking', new_booking_path %>
<% end %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Product:</b>
  <%= @booking.product.name %>
</p>

<p>
  <b>Start at:</b>
  <%= @booking.start_at %>
</p>

<p>
  <b>End at:</b>
  <%= @booking.end_at %>
</p>

<p>
  <b>Description:</b>
  <%= @booking.description %>
</p>

<p>
  <b>Status:</b>
  <%= @booking.status %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>