config/routes.rb
MiniBizspot::Application.routes.draw do

  resources :bookings

  resources :offers

  resources :products

  devise_for :users, :controllers => {
                       :sessions => "users/sessions",
                       :confirmations => "users/confirmations",
                       :passwords => "users/passwords",
                       :registrations => "users/registrations"
                   }

  devise_scope :user do
    get "sign_up" => "users/registrations#new"
    get "sign_in" => "users/sessions#new"
    get "sign_out" => "users/sessions#destroy"
  end
  resources :home do
    collection do
      get :products
      get :offers
    end
  end
  resources :businesses
  resources :profiles
  resources :customer_businesses
  resources :customer_offers

  root :to => 'home#products'

end

app/models/product.rb
class Product < ActiveRecord::Base

  attr_accessible :business_id, :name, :price, :asset, :asset_attributes

  belongs_to :business
  has_one :asset, :as => :owner, :dependent => :destroy
  has_and_belongs_to_many :offers
  has_many :bookings, :dependent => :destroy

  accepts_nested_attributes_for :asset, :allow_destroy => true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authenticate_user!

  before_filter :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @business = Business.find_by_id(params[:business_id])
    @products = @business.products

    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @business = Business.find_by_id(params[:business_id])
    @product = Product.new
    respond_with(@product)
  end

  def edit
    @business = Business.find_by_id(params[:business_id])
  end

  def create
    @product = Product.new(params[:product])
    @product.save
    respond_with(@product)
  end

  def update
    @product.update_attributes(params[:product])
    respond_with(@product)
  end

  def destroy
    @business = Business.find_by_id(params[:business_id])
    @product.destroy
    redirect_to products_path(:business_id => @business.id)
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => {:multipart => true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :business_id, :value => @business.id %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br/>
    <%= f.text_field :price %>
  </div>

  <% f.object.asset ||= Asset.new %>
  <%= f.fields_for :asset do |a| %>
    <div class="field">
      <label>Product Picture</label><br/>
      <%= a.file_field :avatar %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <tr>
    <th>Business</th>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= @business.name %></td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Details', product_path(:id => product.id, :business_id => @business.id) %></td>
      <td><%= link_to 'Edit', edit_product_path(:id => product.id, :business_id => @business.id) %></td>
      <td><%= link_to 'Destroy', product_path(:id => product.id, :business_id => @business.id), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Product', new_product_path(:business_id => @business.id) %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Details</h2>

<p>
  <b>Business:</b>
  <%= @product.business.name %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Product Picture:</b>
</p>
<p>
  <%= image_tag(@product.asset.avatar.url(:medium)) %>
</p>


<%= link_to 'Edit', edit_product_path(:id => @product.id, :business_id => @product.business.id) %> |
<%= link_to 'Back', products_path(:business_id => @product.business.id) %>