config/routes.rb
MiniBizspot::Application.routes.draw do

  resources :bookings

  resources :offers

  resources :products

  devise_for :users, :controllers => {
                       :sessions => "users/sessions",
                       :confirmations => "users/confirmations",
                       :passwords => "users/passwords",
                       :registrations => "users/registrations"
                   }

  devise_scope :user do
    get "sign_up" => "users/registrations#new"
    get "sign_in" => "users/sessions#new"
    get "sign_out" => "users/sessions#destroy"
  end
  resources :home do
    collection do
      get :products
      get :offers
    end
  end
  resources :businesses
  resources :profiles
  resources :customer_businesses
  resources :customer_offers

  root :to => 'home#products'

end

app/views/layouts/_header.html.erb
<% unless current_user %>
  <%= link_to "SIgn In", sign_in_path %> |
  <%= link_to "Sign Up", sign_up_path %>
  <br/>
  <%= link_to "Featured Products", root_path %> |
  <%= link_to "Offers", offers_home_index_path %>
<% else %>
  Hello: <%= current_user.email %> |
  <% if current_user.business_owner? %>
    <%= link_to "Profile", profile_path(current_user.profile) %> |
    <%= link_to "Manage Business", businesses_path %> |
    <%= link_to "Manage Offers", offers_path %> |
    <%= link_to "Manage Bookings",bookings_path %> |
    <%= link_to "Manage Customers" %> |
    <%= link_to "Reports" %> |
  <% else %>
    <%= link_to "Profile", profile_path(current_user.profile) %> |
    <%= link_to "Business", customer_businesses_path %> |
    <%= link_to "Offers", customer_offers_path %> |
    <%= link_to "Bookings", bookings_path %> |
  <% end %>
  <%= link_to "Sign Out", sign_out_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniBizspot</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "layouts/header" %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
<%= render :partial => "layouts/footer" %>
</body>
</html>